version: '3.5'
services:
  java-demo-api:
    container_name: java-demo-api
    hostname: java-demo-api
    platform: ${JAVA_TARGETPLATFORM}
    build:
      context: .
      target: base
      args:
        JAVA_TARGETPLATFORM: ${JAVA_TARGETPLATFORM}
        API_PORT: ${API_PORT}
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
